version: '2'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    links: 
     - mongodb
     - cache
    volumes:
      - .:/dist
  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
     - "27017:27017"
    volumes:
     - /data/db
     #- mongodata:/data/db
  cache:
    image: "redis"
    ports:
     - "6379:6379"
    volumes:
      - /data/cache
      #- mongodata:/data/cache
volumes:
  mongodata:
  